### ISSUE TITLE
Δεν δουλεύει

### ISSUE THREAD

**Issue by petp3t** [everypay/everypay-opencart-2.3#2]
Δεν δουλεύει
1 στις 3 παραγγελίες τις στέλνει λαθος

**Comment by nikosrigas** [comment]
Καλησπέρα σας,

Σε χθεσινή επικοινωνία μαζί σας και σύμφωνα με τα logs που είδαμε μαζί υπάρχει ενα issue οπου κάποια email λειτουργικότητα η οποία δεν σχετίζεται με την EveryPay και το plugin μας, παρουσιάζει κάποιο error και δεν αφήνει το plugin να ολοκληρώσει τη διαδικασία της πληρωμής. 
Έχουν γίνει οι απαραίτητοι έλεγχοι στο plugin και λειτουργεί κανονικά.
Για οποιαδήποτε άλλη λεπτομέρεια, παρακαλώ επικοινωνήστε μαζί μας.

Στη διαθεσή σας
